import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import swaggerAutogen from 'swagger-autogen';


const _dirname = dirname(fileURLToPath(import.meta.url));

const doc = {
  info: {
    title: "Canban API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  definitions: {
    Project: {
      "_id": "61e65cd062cdb8288b0e6484",
      "name": "Тестовый проект",
      "description": "Супер классное описание для тестового проекта"
    },
    Projects: [{$ref: '#/definitions/Project'}],
    NewProject: {
      "name": "Тестовый проект",
      "description": "Супер классное описание для тестового проекта"
    },
    Board: {
      "_id": "61e65d624327f14b2f7bf00c",
      "name": "Тестовая доска",
      "projectId": "61e65cd062cdb8288b0e6484"
    },
    Boards: [{$ref: '#/definitions/Board'}],
    NewBoard: {
      "name": "Тестовая доска",
      "projectId": "61e65cd062cdb8288b0e6484"
    },
    Task: {
      '_id': '61e7de469343e960064dce9e',
      'name': 'Super Task Name 1',
      'description': 'Super Task Description',
      'creator': '61e5364f347b2493b8a42782',
      'assignedTo': '61e5364f347b2493b8a42782',
      'boardId': '61e65d624327f14b2f7bf00c',
      'statusId': '61e65dfa4327f14b2f7bf00e',
      'createdAt': '1970-01-20T00:16:25.670Z',
      'updatedAt': '1970-01-20T00:16:25.670Z',
      'elapsedTime': 1641005765247,
      'id': '61e7de469343e960064dce9e',
    },
    Tasks: [{$ref: '#/definitions/Task'}],
    NewTask: {
      'name': 'Super Task Name 1',
      'description': 'Super Task Description',
      'assignedTo': '61e5364f347b2493b8a42782',
      'boardId': '61e65d624327f14b2f7bf00c',
      'statusId': '61e65dfa4327f14b2f7bf00e',
    },
    Status: {
      "_id": "61e65e4f5914c628f9ae5656",
      "name": "In progress",
      "boardIds": [
        "61e65d624327f14b2f7bf00c"
      ]
    },
    Statuses: [{$ref: '#/definitions/Status'}],
    NewStatus: {
      "name": "New status name",
      "boardId": "61e65d624327f14b2f7bf00c"
    },
    User: {
      "_id": "61e5374b347b2493b8a42783",
      "name": "Kraysik",
      "email": "akrays@aspirity.com"
    },
    Users: [{$ref: '#/definitions/User'}],
    NewUser: {
      "name": "Kraysik",
      "email": "akrays@aspirity.com"
    },
  },
};

// путь и название генерируемого файла
const outputFile = join(_dirname, 'output.json');
// массив путей к роутерам
const endpointsFiles = [
  join(_dirname, '../routes/task/task.js'),
  join(_dirname, '../routes/project/project.js'),
  join(_dirname, '../routes/board/board.js'),
  join(_dirname, '../routes/status/status.js'),
  join(_dirname, '../routes/user/user.js')
];



swaggerAutogen(/*options*/)(outputFile, endpointsFiles, doc).then(({ success }) => {
  console.log(`Generated: ${ success }`);
});
